In [1]:
import pandas as pd
import numpy as np

from dwave.samplers import SimulatedAnnealingSampler
from pyqubo import Binary, LogEncInteger, Placeholder, Constraint
from pathlib import Path

In [2]:
try:
    HERE = Path(__file__)
except NameError:
    HERE = Path().cwd()

DATA = HERE.parent / "data_synthetic"
DATO = HERE.parent / "data_synthetic_out"

DATO.mkdir(exist_ok=True)

WBS_csv = "WBS_Funding_Splits.csv"
CAIS_csv = "CAIS_Deficiencies.csv"
FIM_csv ="FIMS_Master_Scenario_Cost.csv"
QUBO_csv ="Result_QUBO.csv"
FIMS_csv = "FIMS_Inventory.csv"

print(f"HERE: {HERE}")
print(f"DATA: {DATA}")

HERE: /Users/andresrigg/Code/deploy/Experimental_Optimization_Facs/notebooks
DATA: /Users/andresrigg/Code/deploy/Experimental_Optimization_Facs/data_synthetic

In [3]:
FIM_dat = pd.read_csv( (DATA / FIM_csv))
WBS_dat = pd.read_csv((DATA / WBS_csv))
CAIS_sim_dat = pd.read_csv((DATA / CAIS_csv))
FIMS_dat = pd.read_csv((DATA / FIMS_csv))

Project_Type = 'Lab_Type_A'

In [4]:
CAIS_WBS = CAIS_sim_dat.merge(FIMS_dat[['Property_ID','WBS_Element']], on='Property_ID', how='left')
CAIS_WBS_ELMT = CAIS_WBS.merge(WBS_dat[['WBS_Code','Fed_Type_A','Fed_Type_B','Lab_Type_A']], left_on='WBS_Element', right_on='WBS_Code', how='left').rename(columns={'Correction_Cost':'Cost'}).drop(columns={'WBS_Code'})
CAIS_WBS_ID = CAIS_WBS_ELMT[['WBS_Element','Property_ID',Project_Type,'Cost']].groupby(['WBS_Element','Property_ID',Project_Type]).sum().reset_index()

In [5]:
CAIS_WBS_ID['ShareP'] = CAIS_WBS_ID[Project_Type] / 100
CAIS_WBS_ID['ShareS'] = (1 - CAIS_WBS_ID['ShareP'])
CAIS_WBS_ID['cst_P'] = (CAIS_WBS_ID.Cost * CAIS_WBS_ID.ShareP)
CAIS_WBS_ID['cst_S'] = (CAIS_WBS_ID.Cost * CAIS_WBS_ID.ShareS)

In [6]:
CAIS_WBS_ID

,WBS_Element,Property_ID,Lab_Type_A,Cost,ShareP,ShareS,cst_P,cst_S
0,WBS-1.10.01,1938483,100,2219999.0,1.00,0.00,2219999.00,0.00
1,WBS-1.10.01,3094235,100,290834.0,1.00,0.00,290834.00,0.00
2,WBS-1.10.01,4684531,100,3147541.0,1.00,0.00,3147541.00,0.00
3,WBS-1.10.01,5667265,100,2688913.0,1.00,0.00,2688913.00,0.00
4,WBS-1.10.01,6647119,100,2240317.0,1.00,0.00,2240317.00,0.00
5,WBS-1.10.01,7374122,100,2435624.0,1.00,0.00,2435624.00,0.00
6,WBS-1.10.01,8090293,100,939827.0,1.00,0.00,939827.00,0.00
7,WBS-1.10.02,2694522,100,1707590.0,1.00,0.00,1707590.00,0.00
8,WBS-1.10.02,5437923,100,1520519.0,1.00,0.00,1520519.00,0.00
9,WBS-1.10.02,5855124,100,2895298.0,1.00,0.00,2895298.00,0.00
10,WBS-1.10.02,6708456,100,2336362.0,1.00,0.00,2336362.00,0.00
11,WBS-1.10.02,7120868,100,2113286.0,1.00,0.00,2113286.00,0.00
12,WBS-1.10.02,8755439,100,4004887.0,1.00,0.00,4004887.00,0.00
13,WBS-2.05.01,1538552,0,3166573.0,0.00,1.00,0.00,3166573.00
14,WBS-2.05.01,1728977,0,1400232.0,0.00,1.00,0.00,1400232.00
15,WBS-2.05.01,2166941,0,2009542.0,0.00,1.00,0.00,2009542.00
16,WBS-2.05.01,2622631,0,2258498.0,0.00,1.00,0.00,2258498.00
17,WBS-2.05.01,6292423,0,2787047.0,0.00,1.00,0.00,2787047.00
18,WBS-2.05.02,1109031,100,2655122.0,1.00,0.00,2655122.00,0.00
19,WBS-2.05.02,2338687,100,2205198.0,1.00,0.00,2205198.00,0.00
20,WBS-2.05.02,3678638,100,2505343.0,1.00,0.00,2505343.00,0.00
21,WBS-2.05.02,3728882,100,1447806.0,1.00,0.00,1447806.00,0.00
22,WBS-2.05.02,4514944,100,2434218.0,1.00,0.00,2434218.00,0.00
23,WBS-2.05.02,4612365,100,3832960.0,1.00,0.00,3832960.00,0.00
24,WBS-2.05.02,4823498,100,2059228.0,1.00,0.00,2059228.00,0.00
25,WBS-2.05.02,7350753,100,4278470.0,1.00,0.00,4278470.00,0.00
26,WBS-2.05.02,8536477,100,2181821.0,1.00,0.00,2181821.00,0.00
27,WBS-3.01.01,2556017,25,2299350.0,0.25,0.75,574837.50,1724512.50
28,WBS-3.01.01,4226067,25,2745552.0,0.25,0.75,686388.00,2059164.00
29,WBS-3.01.01,5107245,25,1438448.0,0.25,0.75,359612.00,1078836.00
30,WBS-3.01.01,5479144,25,1028839.0,0.25,0.75,257209.75,771629.25
31,WBS-3.01.01,5918715,25,2278299.0,0.25,0.75,569574.75,1708724.25
32,WBS-3.01.01,6440561,25,2344345.0,0.25,0.75,586086.25,1758258.75
33,WBS-3.01.01,7366205,25,1459690.0,0.25,0.75,364922.50,1094767.50
34,WBS-3.02.04,2197935,100,1863562.0,1.00,0.00,1863562.00,0.00
35,WBS-3.02.04,3871230,100,937784.0,1.00,0.00,937784.00,0.00
36,WBS-3.02.04,4905582,100,2874164.0,1.00,0.00,2874164.00,0.00
37,WBS-3.02.04,5528972,100,4115565.0,1.00,0.00,4115565.00,0.00
38,WBS-3.02.04,5663623,100,2071204.0,1.00,0.00,2071204.00,0.00
39,WBS-3.02.04,6960453,100,2613855.0,1.00,0.00,2613855.00,0.00
40,WBS-3.02.04,7022674,100,1790381.0,1.00,0.00,1790381.00,0.00
41,WBS-3.02.04,8606962,100,1715136.0,1.00,0.00,1715136.00,0.00
42,WBS-3.02.04,9961380,100,4049442.0,1.00,0.00,4049442.00,0.00
43,WBS-3.02.04,9996414,100,2401818.0,1.00,0.00,2401818.00,0.00
44,WBS-4.04.01,1768805,75,2762613.0,0.75,0.25,2071959.75,690653.25
45,WBS-4.04.01,2322047,75,3168677.0,0.75,0.25,2376507.75,792169.25
46,WBS-4.04.01,2714803,75,1790273.0,0.75,0.25,1342704.75,447568.25
47,WBS-4.04.01,4842788,75,2586308.0,0.75,0.25,1939731.00,646577.00
48,WBS-4.04.01,5661907,75,1794390.0,0.75,0.25,1345792.50,448597.50
49,WBS-4.04.01,6770619,75,2870202.0,0.75,0.25,2152651.50,717550.50
50,WBS-4.04.01,7067228,75,2241531.0,0.75,0.25,1681148.25,560382.75
51,WBS-4.04.01,7210606,75,1833420.0,0.75,0.25,1375065.00,458355.00
52,WBS-4.04.01,7377459,75,1696541.0,0.75,0.25,1272405.75,424135.25
53,WBS-4.04.01,8707870,75,2312127.0,0.75,0.25,1734095.25,578031.75
54,WBS-4.04.02,3608513,25,1515418.0,0.25,0.75,378854.50,1136563.50
55,WBS-4.04.02,3741438,25,1283626.0,0.25,0.75,320906.50,962719.50

In [7]:
CAIS_WBS_ID[['Property_ID','cst_P','cst_S']]

    Property_ID       cst_P       cst_S
0       1938483  2219999.00        0.00
1       3094235   290834.00        0.00
2       4684531  3147541.00        0.00
3       5667265  2688913.00        0.00
4       6647119  2240317.00        0.00
5       7374122  2435624.00        0.00
6       8090293   939827.00        0.00
7       2694522  1707590.00        0.00
8       5437923  1520519.00        0.00
9       5855124  2895298.00        0.00
10      6708456  2336362.00        0.00
11      7120868  2113286.00        0.00
12      8755439  4004887.00        0.00
13      1538552        0.00  3166573.00
14      1728977        0.00  1400232.00
15      2166941        0.00  2009542.00
16      2622631        0.00  2258498.00
17      6292423        0.00  2787047.00
18      1109031  2655122.00        0.00
19      2338687  2205198.00        0.00
20      3678638  2505343.00        0.00
21      3728882  1447806.00        0.00
22      4514944  2434218.00        0.00
23      4612365  3832960.00        0.00
24      4823498  2059228.00        0.00
25      7350753  4278470.00        0.00
26      8536477  2181821.00        0.00
27      2556017   574837.50  1724512.50
28      4226067   686388.00  2059164.00
29      5107245   359612.00  1078836.00
30      5479144   257209.75   771629.25
31      5918715   569574.75  1708724.25
32      6440561   586086.25  1758258.75
33      7366205   364922.50  1094767.50
34      2197935  1863562.00        0.00
35      3871230   937784.00        0.00
36      4905582  2874164.00        0.00
37      5528972  4115565.00        0.00
38      5663623  2071204.00        0.00
39      6960453  2613855.00        0.00
40      7022674  1790381.00        0.00
41      8606962  1715136.00        0.00
42      9961380  4049442.00        0.00
43      9996414  2401818.00        0.00
44      1768805  2071959.75   690653.25
45      2322047  2376507.75   792169.25
46      2714803  1342704.75   447568.25
47      4842788  1939731.00   646577.00
48      5661907  1345792.50   448597.50
49      6770619  2152651.50   717550.50
50      7067228  1681148.25   560382.75
51      7210606  1375065.00   458355.00
52      7377459  1272405.75   424135.25
53      8707870  1734095.25   578031.75
54      3608513   378854.50  1136563.50
55      3741438   320906.50   962719.50

In [8]:
x = {index : Binary(f"x_{index}") for index in CAIS_WBS_ID.index}
l = {index : f"x_{index}" for index in CAIS_WBS_ID.index}

CAIS_WBS_ID['Qx'] = x
CAIS_WBS_ID['Lx'] = l

###########################################SHAPES
CAIS_WBS_ID_cols = CAIS_WBS_ID.shape[1]
scenario_cols = CAIS_sim_dat.shape[1]
experiment_count = 5

#COST FUNCTIONS
cst_P = CAIS_WBS_ID['cst_P'] @ CAIS_WBS_ID.Qx
cst_S = CAIS_WBS_ID['cst_S'] @ CAIS_WBS_ID.Qx

#REWARDS
A_P = Placeholder('A_P')
A_S = Placeholder('A_S')

#PENALTIES
M_P = Placeholder('M_P')
M_S = Placeholder('M_S')
lambda_P = Placeholder('lambda_P')
lambda_S = Placeholder('lambda_S')

#PARAMTERS
lim_Bp = 5000000
lim_Bs = 3000000

#PARAMETERSMODEL
feed_dict = {
    'A_P' : -1,
    'A_S' : -1,
    'M_P' : 100,
    'M_S' : 100,
    'lambda_P' : 1,
    'lambda_S' : 1
}

#CONSTRAINT TUNINGS
slk_P = LogEncInteger("slk_P", (0, lim_Bp))
slk_S = LogEncInteger("slk_S", (0, lim_Bs))

P_x = Constraint( ((cst_P + slk_P - lim_Bp)/lim_Bp)**2, label = 'P_x', condition=lambda x: abs(x) < lim_Bp*.025 )
S_x = Constraint( ((cst_S + slk_S - lim_Bs)/lim_Bs)**2, label = 'S_x',  condition=lambda x: abs(x) < lim_Bs*.025 )

In [9]:
E_Qx = A_P*(cst_P/lim_Bp) + A_S*(cst_S/lim_Bs) + M_P*(P_x) + M_S*(S_x) + lambda_P*(slk_P/lim_Bp)**2 + lambda_S*(slk_S/lim_Bs)**2

In [10]:
model = E_Qx.compile()
qubo, offset = model.to_qubo(feed_dict=feed_dict)

In [11]:
qubo

{('x_54', 'x_7'): 5.17542524524,
 ('x_50', 'x_14'): 17.437019084400003,
 ('x_54', 'x_54'): -76.452509254294,
 ('x_8', 'x_3'): 32.708346446776,
 ('x_52', 'x_37'): 41.893348563989996,
 ('slk_P[17]', 'x_40'): 1.877350547456,
 ('slk_S[12]', 'slk_S[12]'): -0.2728783890204444,
 ('x_53', 'x_44'): 37.615349079567,
 ('slk_S[17]', 'slk_S[15]'): 0.0963981548657778,
 ('slk_P[11]', 'x_10'): 0.038278955008,
 ('slk_S[12]', 'x_27'): 0.15696896000000002,
 ('slk_S[16]', 'slk_S[6]'): 9.413882311111113e-05,
 ('x_33', 'x_21'): 4.226695880279999,
 ('slk_S[9]', 'x_28'): 0.0234287104,
 ('slk_P[1]', 'x_32'): 9.37738e-06,
 ('slk_S[9]', 'x_47'): 0.0073566094222222225,
 ('x_35', 'x_33'): 2.7377478539199998,
 ('slk_S[4]', 'x_50'): 0.00019924720000000004,
 ('x_40', 'x_38'): 29.665954309792,
 ('slk_P[18]', 'x_47'): 4.067910746111999,
 ('slk_S[19]', 'x_32'): 20.485199189333336,
 ('slk_P[6]', 'x_4'): 0.0011470423040000001,
 ('slk_S[4]', 'x_51'): 0.0001629706666666667,
 ('x_47', 'x_16'): 32.45095247435556,
 ('slk_P[16]', 'x_37'): 2.1577413427199996,
 ('slk_P[12]', 'x_23'): 0.12559843328,
 ('x_47', 'x_27'): 33.698688032199996,
 ('slk_P[8]', 'x_38'): 0.004241825792,
 ('slk_P[11]', 'slk_P[5]'): 5.295308799999999e-07,
 ('slk_P[17]', 'x_51'): 1.4418601574399998,
 ('slk_S[2]', 'x_54'): 0.00010102786666666668,
 ('x_29', 'x_1'): 0.836699171264,
 ('x_38', 'x_24'): 34.12065016409599,
 ('x_30', 'x_14'): 24.010221510800005,
 ('slk_P[8]', 'x_36'): 0.005886287871999999,
 ('x_19', 'x_7'): 30.12459242256,
 ('slk_P[12]', 'x_1'): 0.009530048511999999,
 ('x_55', 'x_35'): 2.407527849568,
 ('x_50', 'x_46'): 23.631830964671003,
 ('slk_S[19]', 'slk_S[10]'): 0.012049769358222225,
 ('slk_P[17]', 'x_22'): 2.552462573568,
 ('x_54', 'x_32'): 46.18461394573001,
 ('x_3', 'x_3'): -79.17329011372401,
 ('x_33', 'x_28'): 52.09951238544,
 ('slk_P[11]', 'slk_P[3]'): 1.3238271999999997e-07,
 ('x_37', 'x_0'): 73.09240147547999,
 ('slk_S[1]', 'x_53'): 2.5690300000000007e-05,
 ('slk_S[16]', 'slk_S[16]'): -4.320867589233778,
 ('x_34', 'x_26'): 32.527669651215994,
 ('slk_P[2]', 'slk_P[0]'): 3.231999999999999e-11,
 ('x_36', 'x_21'): 33.28985507347199,
 ('slk_P[19]', 'x_54'): 1.589030944768,
 ('slk_S[7]', 'x_29'): 0.0030686890666666673,
 ('slk_S[20]', 'slk_S[5]'): 0.000753110584888889,
 ('slk_P[16]', 'x_38'): 1.085907402752,
 ('x_44', 'x_27'): 35.99588047545001,
 ('slk_P[15]', 'x_51'): 0.36046503935999996,
 ('x_52', 'x_48'): 17.927286540496667,
 ('slk_S[13]', 'slk_S[6]'): 1.1767352888888891e-05,
 ('x_55', 'x_25'): 10.983910664439998,
 ('slk_P[8]', 'x_7'): 0.00349714432,
 ('x_55', 'x_4'): 5.751458298884,
 ('slk_P[7]', 'x_35'): 0.000960290816,
 ('slk_S[13]', 'x_33'): 0.19929634133333338,
 ('slk_P[14]', 'slk_P[10]'): 0.00013555990527999996,
 ('slk_P[19]', 'x_36'): 12.055117561855997,
 ('x_10', 'x_2'): 58.830361486735995,
 ('slk_P[21]', 'x_46'): 22.526847614976,
 ('x_55', 'x_14'): 29.956236687200004,
 ('slk_P[19]', 'slk_P[6]'): 0.00027111981055999993,
 ('slk_S[4]', 'x_45'): 0.00028166017777777783,
 ('x_42', 'x_21'): 46.90245139401599,
 ('slk_S[17]', 'slk_S[13]'): 0.02409953871644445,
 ('x_45', 'x_4'): 42.593045703654,
 ('slk_P[1]', 'x_5'): 3.8969984e-05,
 ('slk_P[15]', 'x_8'): 0.39859493273599994,
 ('slk_P[7]', 'x_26'): 0.002234184704,
 ('slk_S[17]', 'x_46'): 1.3036370147555558,
 ('slk_S[13]', 'x_46'): 0.08147731342222224,
 ('slk_P[20]', 'x_42'): 33.969181556736,
 ('x_5', 'x_1'): 5.666898163327999,
 ('slk_P[20]', 'x_44'): 17.380858134527998,
 ('slk_P[18]', 'x_2'): 6.600871903231999,
 ('x_49', 'x_47'): 43.71455543260534,
 ('slk_P[2]', 'x_37'): 0.00013169807999999998,
 ('x_52', 'x_38'): 21.083295032183997,
 ('slk_S[21]', 'x_44'): 13.856791024650002,
 ('slk_P[10]', 'slk_P[0]'): 8.273919999999998e-09,
 ('slk_P[18]', 'x_51'): 2.8837203148799997,
 ('slk_S[11]', 'x_13'): 0.14411425564444444,
 ('x_33', 'x_22'): 7.106407344839999,
 ('slk_P[1]', 'x_11'): 3.3812575999999996e-05,
 ('x_10', 'x_6'): 17.566208714991998,
 ('x_47', 'x_46'): 27.26671791671689,
 ('slk_P[13]', 'x_23'): 0.25119686656,
 ('slk_S[19]', 'slk_S[8]'): 0.003012442339555556,
 ('slk_P[14]', 'x_28'): 0.089966247936,
 ('slk_S[4]', 'slk_S[4]'): -0.0010666637937777777,
 ('x_39', 'x_18'): 55.52083132247999,
 ('x_29', 'x_23'): 11.02702729216,
 ('x_52', 'x_45'): 31.65743262795789,
 ('slk_S[17]', 'x_16'): 6.578352219022222,
 ('x_42', 'x_4'): 72.57627002491199,
 ('slk_P[6]', 'x_49'): 0.001102157568,
 ('x_50', 'x_7'): 22.96569552174,
 ('x_48', 'x_30'): 10.461451008190002,
 ('slk_S[6]', 'x_16'): 0.0032120860444444445,
 ('slk_S[3]', 'x_33'): 0.00019462533333333338,
 ('slk_P[21]', 'x_53'): 29.093290573823992,
 ('slk_P[5]', 'slk_P[2]'): 1.0342399999999997e-09,
 ('slk_S[21]', 'x_45'): 15.893538115405557,
 ('x_54', 'x_37'): 12.47360256234,
 ('x_51', 'x_43'): 26.42124694536,
 ('x_50', 'x_1'): 3.9114805611239998,
 ('slk_S[9]', 'x_46'): 0.00509233208888889,
 ('x_45', 'x_6'): 17.868049193274,
 ('slk_P[16]', 'slk_P[2]'): 2.1181235199999994e-06,
 ('slk_S[15]', 'x_13'): 2.305828090311111,
 ('slk_P[19]', 'x_38'): 8.687259222016,
 ('x_26', 'x_8'): 26.540002280791995,
 ('x_20', 'x_5'): 48.816588312255995,
 ('x_36', 'x_12'): 92.08561631574398,
 ('x_23', 'x_20'): 76.82303604223999,
 ('slk_S[6]', 'x_13'): 0.004503570488888889,
 ('slk_P[15]', 'x_27'): 0.1506902016,
 ('slk_P[17]', 'slk_P[15]'): 0.03470333575167999,
 ('x_45', 'x_20'): 47.63173644726599,
 ('x_43', 'x_25'): 82.20885006767999,
 ('slk_P[1]', 'x_45'): 3.8024124e-05,
 ('slk_S[3]', 'x_31'): 0.00030377320000000003,
 ('x_50', 'x_49'): 37.887030915653995,
 ('slk_P[19]', 'x_26'): 9.151220547584,
 ('slk_S[1]', 'x_45'): 3.520752222222223e-05,
 ('slk_P[15]', 'slk_P[9]'): 0.00013555990527999996,
 ('x_52', 'x_34'): 18.969656034252,
 ('slk_P[12]', 'x_51'): 0.045058129919999995,
 ('slk_S[2]', 'x_31'): 0.00015188660000000002,
 ('slk_P[20]', 'x_6'): 7.883840290815999,
 ('slk_S[0]', 'x_33'): 2.4328166666666672e-05,
 ('slk_S[9]', 'x_48'): 0.005104042666666667,
 ('slk_S[16]', 'x_15'): 2.9266076558222225,
 ('x_26', 'x_21'): 25.270828277807993,
 ('slk_S[9]', 'slk_S[5]'): 3.6772977777777785e-07,
 ('x_22', 'x_7'): 33.25317051696,
 ('slk_P[14]', 'x_34'): 0.244260798464,
 ('x_50', 'x_27'): 29.20636439415,
 ('slk_P[7]', 'x_21'): 0.0014825533439999999,
 ('slk_P[15]', 'x_36'): 0.7534448476159998,
 ('x_28', 'x_18'): 14.579551034687999,
 ('slk_P[17]', 'x_28'): 0.719729983488,
 ('slk_P[11]', 'x_28'): 0.011245780992,
 ('x_50', 'x_11'): 28.421976485195998,
 ('slk_S[11]', 'x_51'): 0.020860245333333336,
 ('slk_P[3]', 'x_34'): 0.000119267968,
 ('x_54', 'x_11'): 6.405023287095999,
 ('slk_P[8]', 'x_4'): 0.0045881692160000005,
 ('slk_P[21]', 'x_26'): 36.604882190336,
 ('slk_P[16]', 'x_48'): 0.7055828582399999,
 ('slk_S[19]', 'x_14'): 16.313885218133336,
 ('slk_P[3]', 'x_5'): 0.000155879936,
 ('slk_P[16]', 'x_39'): 1.37041281024,
 ('slk_P[16]', 'x_45'): 1.245974495232,
 ('x_50', 'x_42'): 54.461698654212,
 ('slk_P[21]', 'slk_P[1]'): 3.388997631999999e-05,
 ('x_47', 'x_44'): 42.075923272067996,
 ('slk_P[15]', 'x_5'): 0.638484217856,
 ('slk_P[20]', 'x_7'): 14.32430313472,
 ('slk_P[5]', 'x_24'): 0.0005271623679999999,
 ('x_26', 'x_0'): 38.749123505431996,
 ('slk_S[17]', 'slk_S[4]'): 4.7069411555555565e-05,
 ('x_31', 'x_10'): 10.645862416476,
 ('slk_P[21]', 'x_40'): 30.037608759296,
 ('x_37', 'x_9'): 95.32629690696,
 ('slk_P[17]', 'slk_P[16]'): 0.06940667150335998,
 ('x_10', 'x_9'): 54.11571380700801,
 ('x_53', 'x_37'): 57.094253740529986,
 ('x_48', 'x_14'): 13.958679436000002,
 ('slk_P[3]', 'x_10'): 0.000149527168,
 ('x_46', 'x_28'): 27.853296488944,
 ('slk_P[9]', 'x_12'): 0.016404017152,
 ('slk_P[4]', 'x_51'): 0.00017600831999999998,
 ('slk_P[19]', 'x_2'): 13.201743806463998,
 ('x_22', 'x_22'): -74.15389451390399,
 ('slk_P[1]', 'x_36'): 4.598662399999999e-05,
 ('x_14', 'x_14'): -72.03054784640001,
 ('slk_S[15]', 'slk_S[12]'): 0.003012442339555556,
 ('x_48', 'x_26'): 23.490226705139996,
 ('slk_P[11]', 'x_1'): 0.0047650242559999995,
 ('slk_P[7]', 'x_51'): 0.0014080665599999998,
 ('x_53', 'x_49'): 39.080265733518,
 ('slk_P[17]', 'slk_P[3]'): 8.472494079999998e-06,
 ('slk_S[12]', 'x_47'): 0.05885287537777778,
 ('x_39', 'x_11'): 44.19058542023999,
 ('slk_S[20]', 'x_55'): 22.432990276266672,
 ('slk_S[5]', 'x_13'): 0.0022517852444444444,
 ('slk_P[2]', 'slk_P[1]'): 6.463999999999998e-11,
 ('x_11', 'x_6'): 15.888985932175997,
 ('x_37', 'x_25'): 140.8665710844,
 ('slk_S[6]', 'x_44'): 0.0009822624000000002,
 ('x_28', 'x_4'): 12.301813639968,
 ('slk_P[21]', 'x_25'): 71.78081533951999,
 ('x_50', 'x_16'): 28.124962669100007,
 ('slk_P[11]', 'x_34'): 0.030532599808,
 ('x_55', 'x_50'): 16.304629004634002,
 ('x_46', 'x_41'): 18.423370032768,
 ('x_51', 'x_30'): 10.68899932982,
 ('slk_P[0]', 'x_8'): 1.2164151999999998e-05,
 ('x_7', 'x_1'): 3.97300184048,
 ('slk_P[1]', 'x_26'): 3.4909136e-05,
 ('slk_P[6]', 'x_41'): 0.0008781496319999999,
 ('slk_S[11]', 'x_47'): 0.02942643768888889,
 ('x_18', 'x_7'): 36.27087820784,
 ('slk_P[12]', 'x_12'): 0.131232137216,
 ('x_33', 'x_25'): 12.490479748599999,
 ('x_51', 'x_7'): 18.7843779468,
 ('slk_S[14]', 'x_45'): 0.2884200220444445,
 ('x_48', 'x_6'): 10.11849702318,
 ('x_41', 'x_5'): 33.419411238912,
 ('slk_P[20]', 'x_39'): 21.92660496384,
 ('slk_P[10]', 'slk_P[5]'): 2.6476543999999993e-07,
 ('x_49', 'x_26'): 37.573601987051994,
 ('slk_S[15]', 'slk_S[1]'): 1.4709191111111114e-06,
 ('slk_P[3]', 'x_38'): 0.000132557056,
 ('slk_P[11]', 'x_11'): 0.034624077823999996,
 ('slk_P[6]', 'x_50'): 0.0008607479039999999,
 ('slk_S[7]', 'x_28'): 0.0058571776,
 ('slk_P[22]', 'x_0'): 14.309172274423998,
 ('slk_P[20]', 'x_27'): 4.8220864512,
 ('x_30', 'x_8'): 3.1287384948819996,
 ('x_49', 'x_36'): 49.49658756676799,
 ('x_39', 'x_10'): 48.855291964079996,
 ('x_44', 'x_41'): 28.429542062207997,
 ('x_50', 'x_28'): 34.874026213968,
 ('x_20', 'x_0'): 44.494871637256,
 ('slk_S[6]', 'x_29'): 0.0015343445333333336,
 ('x_22', 'x_20'): 48.788408214191996,
 ('x_25', 'x_21'): 49.55515629455999,
 ('x_22', 'x_5'): 47.43071825625599,
 ('x_50', 'x_32'): 29.777891289105003,
 ('slk_P[17]', 'x_32'): 0.61455597568,
 ('x_41', 'x_23'): 52.59238146048,
 ('slk_S[8]', 'x_33'): 0.006228010666666668,
 ('slk_P[11]', 'x_43'): 0.039351386111999995,
 ('x_39', 'x_35'): 19.609851178559996,
 ('slk_S[18]', 'x_45'): 4.614720352711112,
 ('slk_S[18]', 'slk_S[3]'): 4.7069411555555565e-05,
 ('slk_P[14]', 'x_43'): 0.31481108889599996,
 ('slk_P[16]', 'x_6'): 0.49274001817599994,
 ('slk_P[12]', 'x_47'): 0.06356110540799999,
 ('slk_S[14]', 'slk_S[7]'): 4.7069411555555565e-05,
 ('slk_P[5]', 'x_27'): 0.0001471584,
 ('slk_P[0]', 'x_32'): 4.68869e-06,
 ('x_25', 'x_23'): 131.1936349696,
 ('slk_P[11]', 'x_33'): 0.005978890239999999,
 ('x_32', 'x_7'): 8.0063601571,
 ('x_53', 'x_40'): 24.837529502322,
 ('slk_P[20]', 'x_2'): 26.403487612927997,
 ('slk_S[18]', 'slk_S[18]'): -16.705081427740446,
 ('x_48', 'x_1'): 3.1312177275599997,
 ('slk_S[13]', 'slk_S[3]'): 1.4709191111111114e-06,
 ('x_41', 'x_20'): 34.376031773183996,
 ('x_43', 'x_10'): 44.892130448928,
 ('slk_P[15]', 'x_19'): 0.578079424512,
 ('x_44', 'x_5'): 40.372119153072,
 ('slk_S[14]', 'slk_S[3]'): 2.941838222222223e-06,
 ('slk_P[9]', 'x_27'): 0.0023545344,
 ('slk_P[14]', 'x_6'): 0.12318500454399998,
 ('slk_S[17]', 'x_45'): 2.307360176355556,
 ('x_30', 'x_10'): 4.807480687436,
 ('slk_P[1]', 'x_2'): 5.036065599999999e-05,
 ('slk_S[8]', 'slk_S[3]'): 4.596622222222223e-08,
 ('slk_P[0]', 'x_36'): 2.2993311999999995e-05,
 ('x_36', 'x_19'): 50.704805635776,
 ('slk_S[11]', 'x_49'): 0.03265652053333334,
 ('slk_S[7]', 'x_14'): 0.003982882133333334,
 ('slk_P[17]', 'slk_P[1]'): 2.1181235199999994e-06,
 ('slk_P[9]', 'slk_P[9]'): -0.02047894093824,
 ('slk_P[14]', 'x_20'): 0.32838031769599996,
 ('slk_P[15]', 'x_6'): 0.24637000908799997,
 ('slk_P[15]', 'x_20'): 0.6567606353919999,
 ('slk_P[8]', 'x_26'): 0.004468369408,
 ('x_35', 'x_30'): 1.9296575055519998,
 ('slk_P[15]', 'x_31'): 0.149310603264,
 ('slk_P[10]', 'x_35'): 0.007682326528,
 ('x_37', 'x_6'): 30.94335285804,
 ('x_46', 'x_7'): 18.342313632419998,
 ('slk_P[21]', 'x_47'): 32.543285968895994,
 ('x_52', 'x_4'): 22.804737860981998,
 ('slk_P[10]', 'x_9'): 0.023718281216,
 ('slk_P[21]', 'x_22'): 40.839401177088,
 ('x_32', 'x_6'): 4.40655745663,
 ('slk_P[3]', 'slk_P[3]'): -0.00031999974143999996,
 ('slk_P[16]', 'x_36'): 1.5068896952319997,
 ('slk_P[0]', 'x_54'): 3.030836e-06,
 ('x_9', 'x_9'): -82.859977564784,
 ('slk_P[5]', 'x_50'): 0.00043037395199999994,
 ('x_48', 'x_12'): 43.117975103579994,
 ('x_51', 'x_33'): 15.1652740922,
 ('slk_P[20]', 'x_11'): 17.727527845887998,
 ('x_49', 'x_33'): 23.741095891820002,
 ('slk_S[18]', 'slk_S[7]'): 0.000753110584888889,
 ('slk_P[15]', 'slk_P[8]'): 6.777995263999998e-05,
 ('slk_P[8]', 'x_55'): 0.0006572165119999999,
 ('slk_S[17]', 'slk_S[17]'): -8.545337023601778,
 ('x_23', 'x_3'): 82.45196777983999,
 ('slk_P[3]', 'x_55'): 2.0538015999999996e-05,
 ('slk_P[20]', 'slk_P[8]'): 0.0021689584844799994,
 ('x_39', 'x_37'): 86.0599212246,
 ('x_32', 'x_2'): 14.757844011289997,
 ('x_55', 'x_55'): -66.69262569880601,
 ('slk_S[14]', 'slk_S[6]'): 2.3534705777777782e-05,
 ('slk_P[0]', 'x_45'): 1.9012062e-05,
 ('x_34', 'x_10'): 34.831643531552,
 ('slk_P[19]', 'slk_P[17]'): 0.5552533720268799,
 ('slk_P[20]', 'slk_P[11]'): 0.017351667875839995,
 ('x_44', 'x_31'): 35.666331133293006,
 ('slk_P[8]', 'x_54'): 0.000775894016,
 ('slk_S[0]', 'x_29'): 2.3974133333333338e-05,
 ('x_44', 'x_10'): 38.726784203436,
 ('slk_P[19]', 'x_48'): 5.644662865919999,
 ('slk_P[17]', 'x_25'): 4.486300958719999,
 ('slk_P[2]', 'x_50'): 5.379674399999999e-05,
 ('slk_P[13]', 'slk_P[9]'): 3.388997631999999e-05,
 ('x_23', 'x_5'): 74.68519493631999,
 ('x_11', 'x_3'): 45.459537584943995,
 ('slk_S[21]', 'x_55'): 19.315340841233336,
 ('slk_P[4]', 'slk_P[4]'): -0.00063999896576,
 ('slk_P[16]', 'x_51'): 0.7209300787199999,
 ('x_30', 'x_3'): 5.532917124014,
 ('x_48', 'x_48'): -74.67626433215001,
 ('x_54', 'x_29'): 28.338049886432007,
 ('slk_P[21]', 'slk_P[10]'): 0.017351667875839995,
 ('x_24', 'x_9'): 47.696629679552,
 ('x_55', 'x_18'): 6.816367264743999,
 ('x_36', 'x_9'): 66.57249024697599,
 ('slk_P[9]', 'x_25'): 0.017524613119999997,
 ('x_47', 'x_4'): 34.764898677816,
 ('x_37', 'x_32'): 19.29660845985,
 ('x_42', 'x_36'): 93.11008333190398,
 ('slk_P[11]', 'x_21'): 0.023720853503999998,
 ('slk_P[17]', 'x_23'): 4.01914986496,
 ('x_33', 'x_33'): -74.16979017535002,
 ('slk_P[20]', 'slk_P[17]'): 1.1105067440537597,
 ('slk_S[8]', 'x_48'): 0.0025520213333333334,
 ('x_55', 'x_52'): 12.340436780107334,
 ('slk_P[22]', 'x_34'): 12.011730501712,
 ('slk_P[4]', 'x_37'): 0.0005267923199999999,
 ('x_45', 'x_22'): 46.27950353751599,
 ('x_21', 'x_2'): 36.45622996036799,
 ('slk_P[21]', 'x_21'): 24.290153988095998,
 ('slk_P[8]', 'x_0'): 0.004546557952,
 ('slk_P[20]', 'x_29'): 3.016644100096,
 ('slk_S[19]', 'x_15'): 23.41286124657778,
 ('slk_S[15]', 'x_48'): 0.3266587306666667,
 ('slk_S[11]', 'slk_S[6]'): 2.941838222222223e-06,
 ('slk_P[7]', 'x_54'): 0.000387947008,
 ('x_48', 'x_29'): 14.626441338080001,
 ('x_42', 'x_25'): 138.60332890991998,
 ('slk_S[0]', 'x_15'): 4.465648888888889e-05,
 ('slk_P[14]', 'x_19'): 0.289039712256,
 ('x_44', 'x_12'): 66.38371733838599,
 ('x_52', 'x_33'): 14.033068949643337,
 ('slk_S[19]', 'slk_S[5]'): 0.0003765552924444445,
 ('slk_S[8]', 'x_45'): 0.004506562844444445,
 ('x_21', 'x_7'): 19.778072380319998,
 ('slk_P[11]', 'x_42'): 0.066346057728,
 ('slk_S[15]', 'x_29'): 0.7855844010666668,
 ('slk_P[5]', 'x_26'): 0.000558546176,
 ('slk_P[4]', 'x_49'): 0.000275539392,
 ('slk_P[1]', 'x_3'): 4.3022608e-05,
 ('slk_P[12]', 'x_50'): 0.05508786585599999,
 ('slk_P[6]', 'x_35'): 0.000480145408,
 ('x_51', 'x_3'): 29.57944123476,
 ('slk_S[16]', 'x_30'): 1.1237665450666667,
 ('x_43', 'x_1'): 5.588242689696,
 ('x_12', 'x_12'): -96.839977868924,
 ('slk_S[7]', 'x_47'): 0.0018391523555555556,
 ('x_21', 'x_19'): 25.541591164704,
 ('slk_S[15]', 'x_46'): 0.32590925368888896,
 ('slk_P[12]', 'x_48'): 0.04409892863999999,
 ('slk_P[6]', 'x_3'): 0.001376723456,
 ('x_6', 'x_3'): 20.216904304408,
 ('x_53', 'x_13'): 40.675105170950005,
 ('x_27', 'x_14'): 53.66039082,
 ('slk_P[6]', 'x_10'): 0.001196217344,
 ('slk_P[3]', 'x_52'): 8.143396799999999e-05,
 ('slk_S[20]', 'x_27'): 40.184053760000005,
 ('slk_S[2]', 'x_27'): 0.00015329000000000002,
 ('slk_S[21]', 'slk_S[4]'): 0.0003242231075555556,
 ('x_55', 'x_54'): 25.287989293684003,
 ('slk_P[15]', 'x_3'): 0.704882409472,
 ('x_53', 'x_35'): 13.009654239407997,
 ('slk_P[4]', 'x_25'): 0.0005476441599999999,
 ('x_44', 'x_25'): 70.91854105266,
 ('x_19', 'x_6'): 16.580036965968002,
 ('slk_P[0]', 'x_3'): 2.1511304e-05,
 ('x_30', 'x_2'): 6.476625869798,
 ('slk_S[7]', 'x_13'): 0.009007140977777777,
 ('x_53', 'x_1'): 4.034670863507999,
 ('x_35', 'x_5'): 18.272713737728,
 ('slk_S[12]', 'slk_S[0]'): 9.193244444444446e-08,
 ('slk_S[6]', 'x_17'): 0.003963800177777779,
 ('slk_S[4]', 'x_29'): 0.0003835861333333334,
 ('slk_S[0]', 'x_27'): 3.8322500000000005e-05,
 ('slk_P[12]', 'x_41'): 0.056201576447999994,
 ('slk_P[21]', 'x_19'): 36.997083168768,
 ('x_42', 'x_33'): 11.821859985959998,
 ('slk_P[5]', 'x_45'): 0.000608385984,
 ('x_37', 'x_36'): 94.63047010127998,
 ('x_10', 'x_8'): 28.419862495023995,
 ('slk_S[20]', 'x_54'): 26.48384907946667,
 ('slk_P[0]', 'x_44'): 1.6575677999999998e-05,
 ('slk_P[0]', 'x_19'): 1.7641584e-05,
 ('slk_S[7]', 'x_31'): 0.0048603712000000006,
 ('slk_P[20]', 'x_12'): 33.595427127296,
 ('slk_S[14]', 'x_54'): 0.4138101418666667,
 ('x_49', 'x_38'): 35.668643179247994,
 ('slk_P[18]', 'slk_P[13]'): 0.017351667875839995,
 ('slk_P[21]', 'x_49'): 36.115499188224,
 ('slk_P[3]', 'x_36'): 0.00018394649599999996,
 ('slk_P[14]', 'x_54'): 0.049657217024,
 ('slk_P[5]', 'x_52'): 0.00032573587199999994,
 ('slk_P[19]', 'x_45'): 9.967795961856,
 ('x_50', 'x_21'): 19.471812185915997,
 ('slk_S[8]', 'x_50'): 0.0031879552000000006,
 ('slk_P[18]', 'x_8'): 3.1887594618879995,
 ('slk_S[19]', 'x_52'): 4.941533821155556,
 ('x_42', 'x_31'): 18.451679318316,
 ('slk_P[6]', 'slk_P[2]'): 2.0684799999999995e-09,
 ('slk_P[0]', 'x_29'): 2.876896e-06,
 ('slk_P[6]', 'x_48'): 0.0006890457599999999,
 ('slk_S[16]', 'x_47'): 0.9416460060444445,
 ('x_28', 'x_5'): 13.374264688895998,
 ('slk_P[9]', 'x_8'): 0.006228045823999999,
 ('slk_P[6]', 'x_36'): 0.0014715719679999997,
 ('x_33', 'x_7'): 4.985104094199999,
 ('slk_P[5]', 'x_10'): 0.000598108672,
 ('slk_S[8]', 'x_30'): 0.004389713066666667,
 ('slk_S[17]', 'slk_S[11]'): 0.006024884679111112,
 ('slk_S[10]', 'x_32'): 0.04001015466666667,
 ('x_10', 'x_7'): 31.916387100639998,
 ('slk_P[2]', 'x_28'): 2.1964416e-05,
 ('slk_S[18]', 'slk_S[15]'): 0.1927963097315556,
 ('x_48', 'x_40'): 19.275850575539998,
 ('slk_S[14]', 'slk_S[11]'): 0.000753110584888889,
 ('slk_P[21]', 'x_44'): 34.761716269055995,
 ('x_32', 'x_13'): 123.72565966141667,
 ('slk_S[12]', 'x_17'): 0.25368321137777783,
 ('slk_P[16]', 'x_3'): 1.409764818944,
 ('slk_S[18]', 'x_47'): 3.766584024177778,
 ('slk_P[6]', 'x_11'): 0.0010820024319999999,
 ('x_49', 'x_32'): 38.12954767691,
 ('x_47', 'x_45'): 48.260473083260884,
 ('slk_S[15]', 'slk_S[4]'): 1.1767352888888891e-05,
 ('slk_S[6]', 'x_32'): 0.002500634666666667,
 ('x_27', 'x_7'): 7.852694133,
 ('slk_P[12]', 'x_24'): 0.06747678310399999,
 ('slk_P[4]', 'x_39'): 0.00033457344,
 ('slk_S[12]', 'slk_S[3]'): 7.354595555555557e-07,
 ('slk_P[13]', 'x_52'): 0.08338838323199999,
 ('x_43', 'x_40'): 34.401354501264,
 ('slk_P[18]', 'x_27'): 1.2055216128,
 ('x_54', 'x_31'): 44.883479081766005,
 ('x_45', 'x_42'): 76.98824236940399,
 ('slk_P[19]', 'x_30'): 1.078815883264,
 ('x_16', 'x_16'): -94.64366359995556,
 ('slk_S[14]', 'x_46'): 0.16295462684444448,
 ('slk_P[14]', 'slk_P[8]'): 3.388997631999999e-05,
 ('slk_P[15]', 'x_25'): 1.1215752396799998,
 ('x_37', 'x_34'): 61.35688434024,
 ('slk_P[21]', 'x_6'): 15.767680581631998,
 ('slk_P[21]', 'x_45'): 39.871183847424,
 ('x_24', 'x_7'): 28.13053712416,
 ('x_29', 'x_0'): 6.386706243103999,
 ('x_40', 'x_11'): 30.268696815727996,
 ('slk_P[14]', 'x_31'): 0.074655301632,
 ('x_24', 'x_1'): 4.791148129215999,
 ('slk_P[8]', 'x_1'): 0.0005956280319999999,
 ('slk_P[3]', 'x_11'): 0.00013525030399999999,
 ('slk_P[15]', 'x_42'): 1.061536923648,

In [12]:
sampler = SimulatedAnnealingSampler()
sampleset = sampler.sample_qubo(qubo, num_reads=1000)
samplesetFrame = sampleset.to_pandas_dataframe()

In [18]:
samplesetFrame.sort_values('energy')

,slk_P[0],slk_P[10],slk_P[11],slk_P[12],slk_P[13],slk_P[14],slk_P[15],slk_P[16],slk_P[17],slk_P[18],...,x_52,x_53,x_54,x_55,x_6,x_7,x_8,x_9,energy,num_occurrences
656,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,-201.997936,1
568,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,-201.996184,1
461,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,-201.994940,1
242,1,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,-201.990957,1
761,0,0,1,1,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,-201.983852,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-199.716107,1
997,0,1,1,1,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,-199.692913,1
132,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-199.673391,1
942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-199.646099,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,-199.332431,1

In [14]:
Property_ID_key = CAIS_WBS_ID[['Property_ID','Lx']].merge(samplesetFrame.sort_values('energy',ascending=True).T.add_prefix('EXP'), how='outer' ,left_on='Lx',right_index=True)
CAIS_WBS_ID = CAIS_WBS_ID.merge(samplesetFrame.sort_values('energy',ascending=True).T.add_prefix('EXP'), how='outer' ,left_on='Lx',right_index=True)

In [15]:
scenario_cols = CAIS_WBS_ELMT.shape[1]
experiment_count = 5

In [16]:
QUBOScenario = pd.merge(CAIS_WBS_ELMT, Property_ID_key, how="left", on='Property_ID', ).iloc[0:,0:(scenario_cols + CAIS_WBS_ID_cols + experiment_count )]
QUBOScenario_all = pd.merge(CAIS_WBS_ELMT, Property_ID_key, how="left", on='Property_ID', )
#QUBOScenario_all

In [17]:
CAIS_WBS_ID.to_csv( (DATO / QUBO_csv) )